### ISSUE TITLE
Could not upload to polymath

### ISSUE THREAD

**Issue by Pinont** [Th0rgal/Polymath#12]
I already setup polymath server and already setup nginx with ssl but when I tried upload onto it 
It send me an error that the server failed to upload or server might down

this is error I receive on polymath server log
```
Oraxen Polymouth Listening on: http://127.0.0.1:8080
Test URL: http://127.0.0.1:8080/debug
======================================================================
[2024-09-10 23:44:37,620] [INFO] Received Upload request from: <server-ip>
[2024-09-10 23:44:37,621] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
  File "polymath/server.py", line 40, in upload
    if not any( [re.compile(x,flags=re.IGNORECASE).fullmatch(User_Agent,flags=re.IGNORECASE) for x in self.config['security']['known_agents']['uploads']] ):
KeyError: 'uploads'
```

This is my Oraxen settings.yml

```
...
  upload:
    enabled: true
    type: polymath #transfer.sh or polymath
    polymath:
      server: my-awesome-subdomain.domain.com # you can also host your own polymath instance
      secret: "oraxen" # change this if you host your own polymath to limit access to resource pack uploading
...
```
Sorry for my English I hope you understand my words

**Comment by makutou** [comment]
me too! 
```
[2024-09-27 16:41:38,943] [INFO] Received Upload request from: 127.0.0.1
[2024-09-27 16:41:38,944] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/Polymath/venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Polymath/venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "polymath/server.py", line 40, in upload
    if not any( [re.compile(x,flags=re.IGNORECASE).fullmatch(User_Agent,flags=re.IGNORECASE) for x in self.config['security']['known_agents']['uploads']] ):
KeyError: 'uploads'
```

**Comment by makutou** [comment]
try modify the settings.toml 
```
known_agents = { upload = ["Apache-HttpClient.*"], download = ["Minecraft Java.*"] } => 
known_agents = { uploads = ["Apache-HttpClient.*"], download = ["Minecraft Java.*"] }
```
may caused by 

`if not any( [re.compile(x,flags=re.IGNORECASE).fullmatch(User_Agent,flags=re.IGNORECASE) for x in self.config['security']['known_agents']['uploads']] ):`

**Comment by Pinont** [comment]
Thanks it's worked!
