### ISSUE TITLE
Known Agents in Pterodactyl

### ISSUE THREAD

**Issue by OhDaveDev** [Th0rgal/Polymath#13]
Hi there, 
I'm running polymath on an internal network on my machine with the server pulling from it also being internal. However, when the plugin loads, it cannot pull from the resource server nor can it upload. I'll post both errors here 

[2024-10-02 20:03:10,650] [INFO] Received Upload request from: 172.18.0.1
[2024-10-02 20:03:10,650] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/polymath/server.py", line 40, in upload
    if not any( [re.compile(x,flags=re.IGNORECASE).fullmatch(User_Agent,flags=re.IGNORECASE) for x in self.config['security']['known_agents']['uploads']] ):
                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'uploads'
[2024-10-02 20:03:10,651] [INFO] 172.18.0.1 [02/Oct/2024:20:03:10 +0000] "POST /upload HTTP/1.1" 500 246 "-" "Apache-HttpClient/4.5.14 (Java/21.0.3)"
[2024-10-02 20:04:12,766] [INFO] 172.18.0.1 [02/Oct/2024:20:04:12 +0000] "POST /upload/upload HTTP/1.1" 404 174 "-" "Apache-HttpClient/4.5.14 (Java/21.0.3)"



[20:04:12 INFO]: Oraxen | Automatic upload of the resource pack is enabled, uploading...
[20:04:12 INFO]: Oraxen | The resource pack could not be uploaded due to a malformed response.
[20:04:12 INFO]: Oraxen | This is usually due to the resourcepack server being down.
[20:04:12 INFO]: Oraxen | Resourcepack not uploaded

**Comment by oOHiyoriOo** [comment]
Hey, If Missing try adding the user agend to the config :D

**Comment by oOHiyoriOo** [comment]
The error suggests there's something wrong with the structure of the python object. 
I'll check later for you.
