### ISSUE TITLE
Issue with the "./run"

### ISSUE THREAD

**Issue by T3Nat** [Th0rgal/Polymath#8]
Hi guys, 

I have a problem when i launch the "run" file, here the issue : 

```
Traceback (most recent call last):
  File "/home/rootmc/polymath/./run", line 2, in <module>
    from polymath import core
  File "polymath/core.py", line 1, in init polymath.core
    from config import TomlConfig
ImportError: cannot import name TomlConfig
```
I don't know how to solve this :/, i have been following the tutorial but i'm blocked right now :/

**Comment by PrevikYT** [comment]
same

**Comment by Gaegeumchi** [comment]
me too

**Comment by PaperXiang** [comment]
well i have this problem,too.How to fix it

**Comment by oOHiyoriOo** [comment]
@T3Nat @PrevikYT @Gaegeumchi @PaperXiang 
Have you built it before running? 
if you're not on Linux but have python installed, just take the command out of `build.sh` and run it. 
on Linux, just do (inside the root folder of this repo): 
1. `chmod +x build.sh`
2. `./build.sh` or `bash build.sh`
3. `python run`

Also, Requirements might be missing, so to install them just `pip install -r requirements.txt`

**Comment by Gaegeumchi** [comment]
@oOHiyoriOo 
It works successfully thanks!

**Comment by T3Nat** [comment]
> @T3Nat @PrevikYT @Gaegeumchi @PaperXiang Have you built it before running? if you're not on Linux but have python installed, just take the command out of `build.sh` and run it. on Linux, just do (inside the root folder of this repo):
> 
> 1. `chmod +x build.sh`
> 2. `./build.sh` or `bash build.sh`
> 3. `python run`
> 
> Also, Requirements might be missing, so to install them just `pip install -r requirements.txt`

I tried it, i got the same error message.

I tried to change the run script with python3 but nothing change : 

![image](https://github.com/oraxen/polymath/assets/72603683/50c071ff-5d70-4bd2-b5e0-c4ad7f6abade)

I also checked if tomlconfig was in the pip3 list and it was here :'( 


![image](https://github.com/oraxen/polymath/assets/72603683/c2e5068b-e38f-4676-9384-3d16d5692b2e)

Maybe there is a correct version ? 

I chmod build.sh and executed it right before :/ 

Do you have any idea ? 

( Sorry for my english, i'm french )

**Comment by oOHiyoriOo** [comment]
Are you sure you're using the right python version? Use `pip3` and `python3` to be sure, or use something like venv / anaconda to prevent such things happening.
